/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoracientifica;
import static Operaciones.Operaciones.*;
import javax.swing.JTextField;

/**
 *
 * @author st3l10s
 */
public class Principal extends javax.swing.JFrame {
    static double resultado;
    static String tipoOperacion;
 
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton0 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonPunto = new javax.swing.JButton();
        jButtonMod = new javax.swing.JButton();
        jButtonRaiz = new javax.swing.JButton();
        jButtonPotencia = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        jButtonDivision = new javax.swing.JButton();
        jButtonLog = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        campoNumero = new javax.swing.JTextField();
        jButtonPer = new javax.swing.JButton();
        jButtonSuma = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonResta = new javax.swing.JButton();
        jButtonMultiplicacion = new javax.swing.JButton();
        jButtonCoseno = new javax.swing.JButton();
        jButtonCotangente = new javax.swing.JButton();
        jButtonCosecante = new javax.swing.JButton();
        jButtonSecante = new javax.swing.JButton();
        jButtonTangente = new javax.swing.JButton();
        jButtonSeno = new javax.swing.JButton();
        campoNumero2 = new javax.swing.JTextField();
        jLabelSigno = new javax.swing.JLabel();
        campoSolucion = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(320, 240));
        setResizable(false);
        setSize(new java.awt.Dimension(90, 0));

        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButtonPunto.setText(".");
        jButtonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPuntoActionPerformed(evt);
            }
        });

        jButtonMod.setText("mod");
        jButtonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModActionPerformed(evt);
            }
        });

        jButtonRaiz.setText("√");
        jButtonRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRaizActionPerformed(evt);
            }
        });

        jButtonPotencia.setText("^");
        jButtonPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPotenciaActionPerformed(evt);
            }
        });

        jButtonIgual.setText("=");
        jButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualActionPerformed(evt);
            }
        });

        jButtonDivision.setText("/");
        jButtonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisionActionPerformed(evt);
            }
        });

        jButtonLog.setText("log");
        jButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogActionPerformed(evt);
            }
        });

        jButtonClear.setText("C");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        campoNumero.setEditable(false);
        campoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroActionPerformed(evt);
            }
        });

        jButtonPer.setText("per");
        jButtonPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerActionPerformed(evt);
            }
        });

        jButtonSuma.setText("+");
        jButtonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumaActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("←");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonResta.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButtonResta.setText("-");
        jButtonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestaActionPerformed(evt);
            }
        });

        jButtonMultiplicacion.setText("X");
        jButtonMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicacionActionPerformed(evt);
            }
        });

        jButtonCoseno.setText("cos");
        jButtonCoseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCosenoActionPerformed(evt);
            }
        });

        jButtonCotangente.setText("ctg");
        jButtonCotangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCotangenteActionPerformed(evt);
            }
        });

        jButtonCosecante.setText("csc");
        jButtonCosecante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCosecanteActionPerformed(evt);
            }
        });

        jButtonSecante.setText("sec");
        jButtonSecante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSecanteActionPerformed(evt);
            }
        });

        jButtonTangente.setText("tan");
        jButtonTangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTangenteActionPerformed(evt);
            }
        });

        jButtonSeno.setText("sen");
        jButtonSeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSenoActionPerformed(evt);
            }
        });

        campoNumero2.setEditable(false);
        campoNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumero2ActionPerformed(evt);
            }
        });

        jLabelSigno.setText(" ");

        campoSolucion.setEditable(false);
        campoSolucion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSolucionActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton10.setText("logN");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoNumero)
                            .addComponent(jButtonPer, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoSolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSeno)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonPotencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButtonLog))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton0)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonPunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonCotangente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonCosecante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonSecante))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonTangente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonMultiplicacion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonBorrar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonCoseno)
                                        .addGap(4, 4, 4)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSeno)
                    .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSigno)
                    .addComponent(campoSolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonResta)
                    .addComponent(jButtonMultiplicacion)
                    .addComponent(jButtonPer)
                    .addComponent(jButtonSuma)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonCoseno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonIgual)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton7)
                                    .addComponent(jButton8)
                                    .addComponent(jButton9)
                                    .addComponent(jButtonClear)
                                    .addComponent(jButtonTangente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton4)
                                    .addComponent(jButton5)
                                    .addComponent(jButton6)
                                    .addComponent(jButtonDivision)
                                    .addComponent(jButtonSecante)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonPotencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRaiz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonMod)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2)
                                    .addComponent(jButton3)
                                    .addComponent(jButtonCotangente)
                                    .addComponent(jButtonCosecante))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton0)
                            .addComponent(jButtonPunto)
                            .addComponent(jButtonLog)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRaizActionPerformed
        jLabelSigno.setText("√");
        tipoOperacion = "√";
    }//GEN-LAST:event_jButtonRaizActionPerformed

    private void jButtonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumaActionPerformed

        jLabelSigno.setText("+");
        tipoOperacion = "+";     
    }//GEN-LAST:event_jButtonSumaActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        if(" ".equals(jLabelSigno.getText())){
            if(campoNumero.getText().length()!=0){
            campoNumero.setText(campoNumero.getText().substring(0, campoNumero.getText().length()-1));
            }
        }
        else if(!" ".equals(jLabelSigno.getText())){
            if(campoNumero2.getText().length()!=0){
            campoNumero2.setText(campoNumero2.getText().substring(0, campoNumero2.getText().length()-1));
            }
        }
        
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(" ".equals(jLabelSigno.getText())){
            campoNumero.setText(campoNumero.getText() + "1");
        }
        else if(!" ".equals(jLabelSigno.getText())){
            campoNumero2.setText(campoNumero2.getText()+ "1");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(" ".equals(jLabelSigno.getText())){
            campoNumero.setText(campoNumero.getText() + "2");
        }
        else if(!" ".equals(jLabelSigno.getText())){
            campoNumero2.setText(campoNumero2.getText()+ "2");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(" ".equals(jLabelSigno.getText())){
            campoNumero.setText(campoNumero.getText() + "3");
        }
        else if(!" ".equals(jLabelSigno.getText())){
            campoNumero2.setText(campoNumero2.getText()+ "3");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(" ".equals(jLabelSigno.getText())){
            campoNumero.setText(campoNumero.getText() + "4");
        }
        else if(!" ".equals(jLabelSigno.getText())){
            campoNumero2.setText(campoNumero2.getText()+ "4");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(" ".equals(jLabelSigno.getText())){
            campoNumero.setText(campoNumero.getText() + "5");
        }
        else if(!" ".equals(jLabelSigno.getText())){
            campoNumero2.setText(campoNumero2.getText()+ "5");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(" ".equals(jLabelSigno.getText())){
            campoNumero.setText(campoNumero.getText() + "6");
        }
        else if(!" ".equals(jLabelSigno.getText())){
            campoNumero2.setText(campoNumero2.getText()+ "6");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(" ".equals(jLabelSigno.getText())){
            campoNumero.setText(campoNumero.getText() + "7");
        }
        else if(!" ".equals(jLabelSigno.getText())){
            campoNumero2.setText(campoNumero2.getText()+ "7");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(" ".equals(jLabelSigno.getText())){
            campoNumero.setText(campoNumero.getText() + "8");
        }
        else if(!" ".equals(jLabelSigno.getText())){
            campoNumero2.setText(campoNumero2.getText()+ "8");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(" ".equals(jLabelSigno.getText())){
            campoNumero.setText(campoNumero.getText() + "9");
        }
        else if(!" ".equals(jLabelSigno.getText())){
            campoNumero2.setText(campoNumero2.getText()+ "9");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        if(" ".equals(jLabelSigno.getText())){
            campoNumero.setText(campoNumero.getText() + "0");
        }
        else if(!" ".equals(jLabelSigno.getText())){
            campoNumero2.setText(campoNumero2.getText()+ "0");
        }
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPuntoActionPerformed
        if(" ".equals(jLabelSigno.getText())){
            campoNumero.setText(campoNumero.getText() + ".");
        }
        else if(!" ".equals(jLabelSigno.getText())){
            campoNumero2.setText(campoNumero2.getText()+ ".");
        }
    }//GEN-LAST:event_jButtonPuntoActionPerformed

    private void jButtonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModActionPerformed
        jLabelSigno.setText("Mod");
        tipoOperacion = "Mod";
    }//GEN-LAST:event_jButtonModActionPerformed

    private void jButtonPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPotenciaActionPerformed
        jLabelSigno.setText("^");
        tipoOperacion = "^";
    }//GEN-LAST:event_jButtonPotenciaActionPerformed

    private void jButtonPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerActionPerformed
        jLabelSigno.setText("Per");
        tipoOperacion = "per";
    }//GEN-LAST:event_jButtonPerActionPerformed

    private void jButtonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestaActionPerformed

        jLabelSigno.setText("-");
        tipoOperacion = "-";   
    }//GEN-LAST:event_jButtonRestaActionPerformed

    private void jButtonMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicacionActionPerformed
        jLabelSigno.setText("*");
        tipoOperacion = "*";
    }//GEN-LAST:event_jButtonMultiplicacionActionPerformed

    private void campoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroActionPerformed
        
    }//GEN-LAST:event_campoNumeroActionPerformed

    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualActionPerformed
            
        switch(tipoOperacion){
            case "+": 
                resultado = sumar(Double.parseDouble(campoNumero.getText()),
                 Double.parseDouble(campoNumero2.getText()));
                campoSolucion.setText(Double.toString(resultado));
                break;
            case "-":
                resultado = restar(Double.parseDouble(campoNumero.getText()),
                 Double.parseDouble(campoNumero2.getText()));
                campoSolucion.setText(Double.toString(resultado));
                break;
            case "*":
                resultado = multiplicar(Double.parseDouble(campoNumero.getText()),
                 Double.parseDouble(campoNumero2.getText()));
                campoSolucion.setText(Double.toString(resultado));
                break;
            case "/":
                resultado = dividir(Double.parseDouble(campoNumero.getText()),
                 Double.parseDouble(campoNumero2.getText()));
                campoSolucion.setText(Double.toString(resultado));
                break;
            case "sen":
                resultado = seno(Double.parseDouble(campoNumero.getText()));
                campoSolucion.setText(Double.toString(resultado));
                break;
            case "cos":
                resultado = coseno(Double.parseDouble(campoNumero.getText()));
                campoSolucion.setText(Double.toString(resultado));
                break;
            case "tan":
                resultado = tangente(Double.parseDouble(campoNumero.getText()));
                campoSolucion.setText(Double.toString(resultado));
                break;
                case "sec":
                resultado = secante(Double.parseDouble(campoNumero.getText()));
                campoSolucion.setText(Double.toString(resultado));
                break;
            case "csc":
                resultado = cosecante(Double.parseDouble(campoNumero.getText()));
                campoSolucion.setText(Double.toString(resultado));
                break;
            case "cot":
                resultado = cotangente(Double.parseDouble(campoNumero.getText()));
                campoSolucion.setText(Double.toString(resultado));
                break;
            case "per":
                resultado = permutacion(Integer.parseInt(campoNumero.getText()),
                 Integer.parseInt(campoNumero2.getText()));
                campoSolucion.setText(Double.toString(resultado));
                break;
            case "^": 
                resultado = potencia(campoNumero.getText(),
                 campoNumero2.getText());
                campoSolucion.setText(Double.toString(resultado));
                break;
             case "√": 
                resultado = calcularRaiz(campoNumero.getText(),
                 campoNumero2.getText());
                campoSolucion.setText(Double.toString(resultado));
                break;
             case "Mod": 
                resultado = mod(campoNumero.getText(),
                 campoNumero2.getText());
                campoSolucion.setText(Double.toString(resultado));
                break;   
             case "LogN": 
                resultado = logaritmoNatural(campoNumero.getText());
                campoSolucion.setText(Double.toString(resultado));
                break;   
            case "Log": 
                resultado = calcularLogaritmosBase10(Double.parseDouble(campoNumero.getText()));
                campoSolucion.setText(Double.toString(resultado));
                break;   
                
        }
    
    }//GEN-LAST:event_jButtonIgualActionPerformed

    private void campoNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumero2ActionPerformed

    }//GEN-LAST:event_campoNumero2ActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        campoNumero.setText("");
        campoNumero2.setText("");
        jLabelSigno.setText(" ");
        campoSolucion.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisionActionPerformed
        jLabelSigno.setText("/");
        tipoOperacion = "/";
    }//GEN-LAST:event_jButtonDivisionActionPerformed

    private void jButtonSenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSenoActionPerformed
        jLabelSigno.setText("sen");
        tipoOperacion = "sen";
    }//GEN-LAST:event_jButtonSenoActionPerformed

    private void jButtonCosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCosenoActionPerformed
        jLabelSigno.setText("cos");
        tipoOperacion = "cos";
    }//GEN-LAST:event_jButtonCosenoActionPerformed

    private void jButtonTangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTangenteActionPerformed
        jLabelSigno.setText("tan");
        tipoOperacion = "tan";
    }//GEN-LAST:event_jButtonTangenteActionPerformed

    private void jButtonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogActionPerformed
        jLabelSigno.setText("Log");
        tipoOperacion = "Log";
    }//GEN-LAST:event_jButtonLogActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jLabelSigno.setText("LogN");
        tipoOperacion = "LogN";
    }//GEN-LAST:event_jButton10ActionPerformed

    private void campoSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSolucionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoSolucionActionPerformed

    private void jButtonSecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSecanteActionPerformed
       jLabelSigno.setText("sec");
        tipoOperacion = "sec";
    }//GEN-LAST:event_jButtonSecanteActionPerformed

    private void jButtonCosecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCosecanteActionPerformed
       jLabelSigno.setText("csc");
        tipoOperacion = "csc";
    }//GEN-LAST:event_jButtonCosecanteActionPerformed

    private void jButtonCotangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCotangenteActionPerformed
       jLabelSigno.setText("cot");
        tipoOperacion = "cot";
    }//GEN-LAST:event_jButtonCotangenteActionPerformed

    
//    private double Operacion(double valor1, double valor2){
//    switch(tipoOperacion){
//        case "+":
//            resultado = sumar(valor1, valor2);
//            campoNumero.setText(Double.toString(resultado));
//         break;
//    }
//    return resultado;
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoNumero2;
    private javax.swing.JTextField campoSolucion;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonCosecante;
    private javax.swing.JButton jButtonCoseno;
    private javax.swing.JButton jButtonCotangente;
    private javax.swing.JButton jButtonDivision;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonLog;
    private javax.swing.JButton jButtonMod;
    private javax.swing.JButton jButtonMultiplicacion;
    private javax.swing.JButton jButtonPer;
    private javax.swing.JButton jButtonPotencia;
    private javax.swing.JButton jButtonPunto;
    private javax.swing.JButton jButtonRaiz;
    private javax.swing.JButton jButtonResta;
    private javax.swing.JButton jButtonSecante;
    private javax.swing.JButton jButtonSeno;
    private javax.swing.JButton jButtonSuma;
    private javax.swing.JButton jButtonTangente;
    private javax.swing.JLabel jLabelSigno;
    // End of variables declaration//GEN-END:variables
}
